-- RunUp backend schema — Postgres (Vercel Postgres / Neon). Every statement is idempotent
-- (CREATE ... IF NOT EXISTS), so re-running this whole file after it's grown new tables is safe —
-- no need to track which snippet you already ran. See IOS_SETUP.md § "Backend (comptes, clubs,
-- activités)".
--
-- v1 scope: a user belongs to at most one club at a time — enforced in application code
-- (api/clubs/*.js), not a DB constraint, so multi-club support later doesn't need a migration.

CREATE EXTENSION IF NOT EXISTS pgcrypto; -- gen_random_uuid()

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE,
  password_hash TEXT,
  apple_sub TEXT UNIQUE,
  name TEXT NOT NULL,
  xp_total INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Short, optional, self-authored status shown on a member's club profile — moderated the same
-- way as everything else user-generated (lib/moderation.js's blocklist filter).
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT;

-- A real profile photo. `avatar_data` (legacy) held a full base64 data URI inline in Postgres —
-- cheap at first, but it meant every leaderboard/feed/comments row that included an avatar was
-- shipping a several-hundred-KB blob down the wire even when only a 40pt circle was ever drawn
-- from it. `avatar_url` (current) points at a real object in Vercel Blob storage instead — rows
-- carry a short URL, and the client fetches/caches the actual image itself, once, only where it's
-- shown. `avatar_data` stays for any account that uploaded a photo before this migration; new and
-- re-uploaded avatars always go through avatar_url (see api/account/avatar.js).
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_data TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT;

-- Real referral loop — every user gets a personal code (generated at signup, see
-- api/auth/[action].js) to share; `referred_by` is set once, at signup, from whatever code (if
-- any) the new signup provided; `referral_reward_granted` flips once, the first time the referred
-- person logs a real activity (api/activities/[action].js) — a reward for a signup that actually
-- became a real user, not just an install. Postgres allows multiple NULLs under UNIQUE, so
-- existing rows (no code yet) don't collide with each other or with a fresh code.
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_code TEXT UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referred_by UUID REFERENCES users(id);
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_reward_granted BOOLEAN NOT NULL DEFAULT false;

-- Opt-in to the global weekly leaderboard (across every club, not just her own) — off by default,
-- a real explicit choice since it's a bigger visibility surface than the club-scoped leaderboard.
ALTER TABLE users ADD COLUMN IF NOT EXISTS global_leaderboard_opt_in BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS clubs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  invite_code TEXT UNIQUE NOT NULL,
  created_by UUID NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- L'ANNUAIRE DE CLUBS.
--
-- Jusqu'ici un club ne se rejoignait QUE par code d'invitation : il fallait déjà connaître
-- quelqu'un dedans pour y entrer. C'est cohérent pour un club d'amis, et c'est une impasse pour
-- un compte neuf — or le club est le mécanisme de rétention le mieux documenté de l'app (défis,
-- classement, fil), et il ne servait à personne n'ayant pas déjà un contact.
--
-- `is_public` est un OPT-IN, à false par défaut : cette migration ne rend visible aucun club
-- existant, et seul le créateur peut le basculer. Le code d'invitation continue de fonctionner
-- exactement pareil, pour les clubs privés comme publics.
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS is_public BOOLEAN NOT NULL DEFAULT false;
-- Où le club court. Texte libre saisi par le créateur : l'app n'a ni géolocalisation de club ni
-- référentiel de villes, et en bâtir un pour trier un annuaire de cette taille serait
-- disproportionné.
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS city TEXT;
-- Index partiel : l'annuaire ne lit que les clubs publics, qui resteront une petite minorité.
CREATE INDEX IF NOT EXISTS idx_clubs_public ON clubs(is_public) WHERE is_public;

CREATE TABLE IF NOT EXISTS club_members (
  club_id UUID NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (club_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_club_members_user ON club_members(user_id);

CREATE TABLE IF NOT EXISTS activities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Idempotency key generated by the app (a UUID per completed run/goal) — a retried POST (flaky
  -- network) must not double-count XP or duplicate the feed entry.
  client_id UUID NOT NULL UNIQUE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  club_id UUID REFERENCES clubs(id) ON DELETE SET NULL,
  type TEXT NOT NULL, -- 'run' | 'strength' | 'badge'
  text TEXT NOT NULL, -- human-readable, e.g. "a couru 8.2 km · Sortie longue"
  xp_earned INTEGER NOT NULL DEFAULT 0,
  -- Structured distance for 'run' activities — NULL for 'strength'/'badge'. Lets real challenge
  -- progress (see `challenges` below) be a real SUM() instead of parsing it back out of `text`.
  distance_km NUMERIC,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- CREATE TABLE IF NOT EXISTS is a no-op on a table that already exists — this ALTER is what
-- actually adds distance_km to a database from before this column existed.
ALTER TABLE activities ADD COLUMN IF NOT EXISTS distance_km NUMERIC;

CREATE INDEX IF NOT EXISTS idx_activities_club_created ON activities(club_id, created_at DESC);
-- The referral "isFirstActivity" check (api/activities/[action].js) runs a user_id-scoped query
-- on EVERY activity creation, unindexed on that column before this — a full scan on the app's
-- hottest write path once the table has real volume.
CREATE INDEX IF NOT EXISTS idx_activities_user ON activities(user_id);

CREATE TABLE IF NOT EXISTS activity_kudos (
  activity_id UUID NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (activity_id, user_id)
);

-- Real comments on a club-mate's activity — several per activity, per user, unlike kudos (one
-- toggle per user). Moderated the same way as everything else user-generated: the blocklist filter
-- at submission (lib/moderation.js) plus the report mechanism (target_type 'comment').
CREATE TABLE IF NOT EXISTS activity_comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  activity_id UUID NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_activity_comments_activity_created ON activity_comments(activity_id, created_at ASC);

-- Real, permanent achievements — the client computes eligibility from data only it has (streak,
-- run history, elevation) and syncs earned keys up via api/clubs/syncBadges; once a row exists
-- here it stays (an achievement doesn't un-earn itself if the underlying streak later resets).
-- This is what makes badges visible on OTHER members' club profiles, not just your own device.
CREATE TABLE IF NOT EXISTS user_badges (
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  badge_key TEXT NOT NULL,
  earned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, badge_key)
);

-- Moderation (App Store guideline 1.2 — user-generated content: club names, display names, and
-- the activity feed need a block + report mechanism, not just a content filter at creation time).

CREATE TABLE IF NOT EXISTS blocks (
  blocker_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  blocked_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (blocker_id, blocked_id)
);

CREATE TABLE IF NOT EXISTS reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reporter_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  target_type TEXT NOT NULL, -- 'user' | 'club' | 'activity'
  target_id UUID NOT NULL,
  reason TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Any member can set a club challenge (a distance target by a deadline) — replaces what used to
-- be a fixed "100 km ce mois-ci" shown to everyone regardless of the real club. Progress is a real
-- SUM() over `activities.distance_km` logged since the challenge was created (see
-- api/clubs/[action].js), not tracked as a running counter here.
CREATE TABLE IF NOT EXISTS challenges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  club_id UUID NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  created_by UUID NOT NULL REFERENCES users(id),
  title TEXT NOT NULL,
  target_km NUMERIC NOT NULL,
  end_date DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_challenges_club_end ON challenges(club_id, end_date DESC);

-- Real APNs push (kudos received, a club-mate posts an activity) — one row per device a user has
-- signed in from. `token` is unique on its own (not per-user): the same physical device
-- re-registering after a sign-out/sign-in as a *different* account must move the token to the new
-- owner, not create a stale duplicate still pointing at the old one.
CREATE TABLE IF NOT EXISTS device_tokens (
  token TEXT PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  platform TEXT NOT NULL DEFAULT 'ios',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_device_tokens_user ON device_tokens(user_id);

-- Real Strava OAuth connection (see lib/strava.js, api/strava/[action].js) — tokens live only
-- server-side, the client_secret must never reach the app. `expires_at` drives when a stored
-- access token gets refreshed before the next call to Strava's API.
CREATE TABLE IF NOT EXISTS strava_connections (
  user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  strava_athlete_id BIGINT NOT NULL,
  access_token TEXT NOT NULL,
  refresh_token TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  connected_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- Corrective migrations (idempotent) — run after any of the tables above
-- already exist. Fresh databases get the same end state from the blocks below
-- because every statement here is a no-op once applied.
-- ============================================================================

-- Account deletion used to 500 with an FK violation for anyone who had created a club or a
-- challenge, or referred someone: these three columns referenced users(id) with no ON DELETE
-- action. App Store guideline 5.1.1(v) requires deletion to actually work — the creator's row
-- going away shouldn't take the club/challenge down with it, just detach it.
-- Each DROP/ADD pair is guarded so a re-run is a true no-op: the bare pair re-ran DROP+ADD every
-- time (ACCESS EXCLUSIVE lock + full FK re-validation), and a run dying between the two
-- statements (autocommit, no transaction) would leave the FK missing entirely. The guard checks
-- the delete rule: already ON DELETE SET NULL ('n') → skip.
ALTER TABLE clubs ALTER COLUMN created_by DROP NOT NULL;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'clubs_created_by_fkey' AND confdeltype = 'n'
  ) THEN
    ALTER TABLE clubs DROP CONSTRAINT IF EXISTS clubs_created_by_fkey;
    ALTER TABLE clubs ADD CONSTRAINT clubs_created_by_fkey
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
  END IF;
END $$;

ALTER TABLE challenges ALTER COLUMN created_by DROP NOT NULL;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'challenges_created_by_fkey' AND confdeltype = 'n'
  ) THEN
    ALTER TABLE challenges DROP CONSTRAINT IF EXISTS challenges_created_by_fkey;
    ALTER TABLE challenges ADD CONSTRAINT challenges_created_by_fkey
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'users_referred_by_fkey' AND confdeltype = 'n'
  ) THEN
    ALTER TABLE users DROP CONSTRAINT IF EXISTS users_referred_by_fkey;
    ALTER TABLE users ADD CONSTRAINT users_referred_by_fkey
      FOREIGN KEY (referred_by) REFERENCES users(id) ON DELETE SET NULL;
  END IF;
END $$;

-- One club per user, enforced by the database — the app-level check was check-then-insert, so a
-- double-submitted "join" raced into membership of two clubs at once, and every
-- `memberRows[0]` in the API then picked one arbitrarily.
CREATE UNIQUE INDEX IF NOT EXISTS uniq_club_members_user ON club_members(user_id);

-- Sorties de groupe — a member proposes a real group run (title, meeting point, date/time), the
-- others RSVP. Creator deletion detaches (SET NULL) rather than cancelling the event, same
-- policy as clubs/challenges.
CREATE TABLE IF NOT EXISTS club_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  club_id UUID NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  location TEXT,
  starts_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_club_events_club_starts ON club_events(club_id, starts_at);

CREATE TABLE IF NOT EXISTS event_rsvps (
  event_id UUID NOT NULL REFERENCES club_events(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (event_id, user_id)
);

-- Daily request counter behind api/coach.js's rate limit — keyed by user id when signed in,
-- client IP otherwise. Rows are tiny and only ever grow by one per key per day; prune old days
-- opportunistically if it ever matters.
CREATE TABLE IF NOT EXISTS coach_usage (
  key TEXT NOT NULL,
  day DATE NOT NULL,
  count INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (key, day)
);

-- Idempotency keys, same pattern as activities.client_id above — createEvent/createChallenge had
-- no protection beyond a client-side isSaving flag, so a request that timed out client-side after
-- the server already processed it (then retried, by the user re-tapping after seeing a spinner
-- hang) could insert a duplicate row and re-notify the whole club a second time. Nullable: existing
-- rows predate this and stay NULL, which is fine since Postgres allows any number of NULLs under a
-- UNIQUE constraint — only new, client-generated ids need to actually be unique.
ALTER TABLE club_events ADD COLUMN IF NOT EXISTS client_id UUID UNIQUE;
ALTER TABLE challenges ADD COLUMN IF NOT EXISTS client_id UUID UNIQUE;

-- Real friends/follow graph — a lighter social option alongside the club, for someone who wants
-- a feed of people she's chosen directly rather than the shared leaderboard/challenges/invite-
-- code "esprit club". One-way by default (follow anyone, no confirmation, like Strava); `status`
-- only ever starts as 'pending' when the followee has gone private (see `is_private` below), and
-- flips to 'accepted' once they approve (api/friends/[action].js `respond`) — same distinction
-- Instagram makes between a public and a private account.
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_private BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS follows (
  follower_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  followee_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'accepted', -- 'pending' | 'accepted'
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (follower_id, followee_id),
  CHECK (follower_id != followee_id)
);

CREATE INDEX IF NOT EXISTS idx_follows_followee_status ON follows(followee_id, status);
CREATE INDEX IF NOT EXISTS idx_follows_follower_status ON follows(follower_id, status);

-- A first name alone (all onboarding/signup ever asked for) makes "search someone to follow" a
-- coin flip once there's more than one Léo on the platform — these two fields let a real search
-- disambiguate: a chosen, unique handle (api/account/profile.js), and a last name to search
-- "nom prénom" the way a real person actually thinks of someone. Both nullable: nobody had either
-- before this, and a username in particular is opt-in (see api/account/profile.js's validation).
ALTER TABLE users ADD COLUMN IF NOT EXISTS username TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS uniq_users_username_lower ON users (lower(username));

-- `blocks` only ever had its PRIMARY KEY (blocker_id, blocked_id) as an index, which Postgres
-- cannot use for a lookup on blocked_id alone — the leading column is missing, so it falls back to
-- a sequential scan of the whole table. Two hot WRITE paths do exactly that lookup, on every
-- single call, before any push goes out:
--   - notifyClubOfNewActivity (api/activities/[action].js) — runs on every activity posted, i.e.
--     the app's most frequent write;
--   - handleCreateEvent (api/clubs/[action].js) — runs on every group run created.
-- Both filter club members with `NOT IN (SELECT blocker_id FROM blocks WHERE blocked_id = ...)`,
-- so the scan cost grows with the total number of blocks on the platform, not with the club's
-- size. This index turns each one into an index lookup.
CREATE INDEX IF NOT EXISTS idx_blocks_blocked ON blocks(blocked_id);

-- Session-token revocation (see lib/auth.js). Our own JWTs are stateless — until this table, the
-- only thing that ever invalidated one was its own expiry, so "se déconnecter" was purely a
-- client-side gesture (drop the copy in the Keychain) and a stolen token stayed valid for months.
-- One row per explicitly signed-out token, keyed by the `jti` claim now embedded in every issued
-- token; `requireAuth` refuses any token whose jti is listed here. Scoped to one token on purpose:
-- signing out on one device must not sign out her other devices.
-- `expires_at` mirrors the token's own `exp` and exists only so rows can be dropped once the token
-- they name would have expired anyway (pruned opportunistically in api/auth/[action].js — a
-- revoked token past its expiry is already refused by signature verification).
CREATE TABLE IF NOT EXISTS revoked_tokens (
  jti TEXT PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_revoked_tokens_expires ON revoked_tokens(expires_at);

-- The client's own computed "this week's planned km" (sum of the current week's session
-- durations/paces — see `UserProfile.plannedWeeklyKm`), pushed up via api/clubs/syncWeeklyTarget
-- whenever Club loads. Lets the weekly leaderboard rank by % of each member's OWN plan instead of
-- raw km, so a mixed-level club stays motivating for a beginner on a 15 km week next to a
-- marathoner on a 60 km week. Nullable + no default: NULL (not 0) for any member who hasn't
-- opened Club since this shipped, so the leaderboard can tell "no target on record" apart from "a
-- genuine 0 km week" and fall back to km-only ranking for that member instead of dividing by zero.
ALTER TABLE users ADD COLUMN IF NOT EXISTS weekly_target_km NUMERIC;

-- Behavioural analytics — first-party, on the Postgres this backend already runs (see
-- api/events.js and RunUp/Services/Analytics.swift). Deliberately NOT a third-party SDK: any
-- analytics vendor means a new sub-traitant to declare in PRIVACY_POLICY.md, a new "Tracking"
-- answer in App Store Connect's privacy questionnaire, and an account/API key that doesn't exist
-- yet — for numbers this one table already answers (where onboarding leaks, whether a first run
-- ever happens, who comes back).
--
-- `user_id` is nullable, ON DELETE SET NULL, for two reasons that happen to want the same column
-- shape: the decisive part of the funnel is pre-account (onboarding completes long before Club
-- ever asks anyone to sign in, and most users never sign in at all), and account deletion
-- (guideline 5.1.1(v)) must not take the rest of the funnel's history down with it — dropping the
-- id leaves a row that is no longer about anyone in particular.
-- `anonymous_id` is the device-scoped id the client generates on first launch: the only way to
-- follow one person through the pre-account funnel at all, and — since the same device keeps
-- sending it after sign-in — what lets those earlier events be stitched back to a real user id.
CREATE TABLE IF NOT EXISTS events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  anonymous_id TEXT,
  name TEXT NOT NULL,
  props JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The two shapes every question about this table takes: "how many X over the last N days" (funnel,
-- conversion, retention) and "everything this one account did, most recent first" (support, or
-- debugging one report). Unindexed, both are sequential scans over what will be by far the
-- fastest-growing table here — one row per meaningful tap, against one row per completed run
-- everywhere else.
CREATE INDEX IF NOT EXISTS idx_events_name_created ON events(name, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_user_created ON events(user_id, created_at DESC);

-- DAU/WAU/MAU and D7/D30 retention were literally uncomputable before this column: `created_at`
-- says when an account was made, and nothing anywhere said whether it was ever used again.
-- Written opportunistically by api/events.js on every authenticated batch (free — that request is
-- already a write) rather than through a dedicated heartbeat endpoint nobody would remember to
-- call. Nullable with no default: no account predating this migration has a value that could be
-- backfilled honestly, and NULL says exactly that, where a fabricated `now()` would make every
-- dormant account look active in the first retention query anyone runs.
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;

-- Real per-run metrics on a posted activity. Until now `activities` carried only `distance_km`
-- (added for challenge progress) plus a prose `text` — so the club/friends feed could show WHO ran
-- and a sentence, but never the run itself. Every richer feed card design dies on that: duration,
-- pace and elevation aren't styling, they're columns that didn't exist, and no amount of client
-- work can render a number the API never sends.
--
-- All nullable, deliberately: 'strength' and 'badge' activities have no pace, and a run logged
-- manually (AddRunSheet) or marked done without GPS has no elevation. NULL means "not applicable
-- or not measured" and the client omits the metric rather than printing a fabricated 0 — the same
-- rule that got a hardcoded VO2max removed from this app.
ALTER TABLE activities ADD COLUMN IF NOT EXISTS duration_seconds INTEGER;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS avg_pace TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS elevation_gain_m INTEGER;
-- Set by the client only when it genuinely verified the run beat every prior real run (see
-- `RecapView.recordKind`) — never inferred server-side, where the run history to compare against
-- doesn't exist.
ALTER TABLE activities ADD COLUMN IF NOT EXISTS is_personal_record BOOLEAN NOT NULL DEFAULT false;

-- ---------------------------------------------------------------------------
-- Shared routes — "I'm somewhere new, where do I run?"
-- ---------------------------------------------------------------------------
-- The one thing no running app answers well: you're in a city for three days and
-- you have no idea where to run. Strava and Komoot have route libraries, but a
-- coaching app is where the question actually gets asked, right next to "what's
-- my session today?".
--
-- A route is NOT an activity, and deliberately gets its own table rather than
-- more columns on `activities`. It has a different lifetime (it stays useful for
-- years after the run that produced it), a different audience (strangers in the
-- same city, not your club), and its own moderation surface (a name and, later,
-- a photo that anyone can see).
--
-- PRIVACY — the part that must not be got wrong. Until this feature, GPS traces
-- never left the phone. Publishing one is the first time a user's precise
-- movements reach the server, and a raw trace starts and ends at a home address.
-- Two rules, both enforced on the DEVICE, before upload:
--   1. Publication is explicit, per run. Never automatic, never a global toggle
--      that back-fills history.
--   2. The first and last 300 m are cut off (see RouteGeometry.trimmedForSharing).
-- Trimming client-side rather than here is the whole point: a server that never
-- receives the endpoints cannot leak them, whatever happens to it later.
CREATE TABLE IF NOT EXISTS routes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Same idempotency contract as `activities`: the app generates this once per
  -- publication, so a retried POST on a flaky connection can't duplicate a route.
  client_id UUID NOT NULL UNIQUE,
  -- CASCADE, not SET NULL: `api/account/[action].js` promises that deleting an
  -- account leaves nothing of the person behind, and a trace of their runs is
  -- exactly the kind of thing that promise is about. Losing the route from the
  -- map is the correct price.
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- User-supplied, so it goes through lib/moderation.js like club names do.
  name TEXT NOT NULL,
  -- Free text from the author: "plat, le long du fleuve", "ça grimpe au km 3".
  notes TEXT,
  distance_km NUMERIC NOT NULL,
  elevation_gain_m INTEGER,
  -- Indicative only — how long it took the person who published it, not a target.
  duration_seconds INTEGER,
  -- The trimmed, decimated trace: [[lat, lng], …]. JSONB rather than a geometry
  -- type because there is no PostGIS on this database and none is needed: nothing
  -- here does geometry, it draws a line and filters by a rectangle.
  points JSONB NOT NULL,
  -- A ~24-point version of the same trace, precomputed on the device. The discovery list draws
  -- fifty routes at once; sending each one's full trace would be megabytes over a mobile
  -- connection to draw squiggles a few millimetres wide. The full `points` is fetched only when
  -- one route is opened.
  preview_points JSONB NOT NULL,
  -- First point OF THE TRIMMED TRACE — i.e. ~300 m from where the run really
  -- started. This is what pins the route on the discovery map.
  start_lat NUMERIC NOT NULL,
  start_lng NUMERIC NOT NULL,
  -- Reverse-geocoded on the device (CLGeocoder) and sent as text, so the server
  -- needs no geocoding provider, no API key and no per-request cost.
  locality TEXT,
  country_code TEXT,
  photo_url TEXT,
  saves_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Discovery is "routes starting inside the map's current viewport", so a plain
-- composite btree on the start point serves it. A route whose start falls just
-- outside the viewport is missed; at this scale that is the right trade against
-- carrying a GiST/box index for overlap testing, and the client already queries a
-- rectangle padded well beyond what it draws.
CREATE INDEX IF NOT EXISTS idx_routes_start ON routes(start_lat, start_lng);
-- "Most saved first" is the default ordering of the discovery list.
CREATE INDEX IF NOT EXISTS idx_routes_saves ON routes(saves_count DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_routes_user ON routes(user_id, created_at DESC);

-- Saving a route is the real quality signal (a kudos costs nothing; saving means
-- "I intend to run this"), and it is also the user's own list of routes to try.
CREATE TABLE IF NOT EXISTS route_saves (
  route_id UUID NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (route_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_route_saves_user ON route_saves(user_id, created_at DESC);
