-- RunUp backend schema — Postgres (Vercel Postgres / Neon). Every statement is idempotent
-- (CREATE ... IF NOT EXISTS), so re-running this whole file after it's grown new tables is safe —
-- no need to track which snippet you already ran. See IOS_SETUP.md § "Backend (comptes, clubs,
-- activités)".
--
-- v1 scope: a user belongs to at most one club at a time — enforced in application code
-- (api/clubs/*.js), not a DB constraint, so multi-club support later doesn't need a migration.

CREATE EXTENSION IF NOT EXISTS pgcrypto; -- gen_random_uuid()

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE,
  password_hash TEXT,
  apple_sub TEXT UNIQUE,
  name TEXT NOT NULL,
  xp_total INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Short, optional, self-authored status shown on a member's club profile — moderated the same
-- way as everything else user-generated (lib/moderation.js's blocklist filter).
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT;

-- Real referral loop — every user gets a personal code (generated at signup, see
-- api/auth/[action].js) to share; `referred_by` is set once, at signup, from whatever code (if
-- any) the new signup provided; `referral_reward_granted` flips once, the first time the referred
-- person logs a real activity (api/activities/[action].js) — a reward for a signup that actually
-- became a real user, not just an install. Postgres allows multiple NULLs under UNIQUE, so
-- existing rows (no code yet) don't collide with each other or with a fresh code.
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_code TEXT UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referred_by UUID REFERENCES users(id);
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_reward_granted BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS clubs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  invite_code TEXT UNIQUE NOT NULL,
  created_by UUID NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS club_members (
  club_id UUID NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (club_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_club_members_user ON club_members(user_id);

CREATE TABLE IF NOT EXISTS activities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Idempotency key generated by the app (a UUID per completed run/goal) — a retried POST (flaky
  -- network) must not double-count XP or duplicate the feed entry.
  client_id UUID NOT NULL UNIQUE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  club_id UUID REFERENCES clubs(id) ON DELETE SET NULL,
  type TEXT NOT NULL, -- 'run' | 'strength' | 'badge'
  text TEXT NOT NULL, -- human-readable, e.g. "a couru 8.2 km · Sortie longue"
  xp_earned INTEGER NOT NULL DEFAULT 0,
  -- Structured distance for 'run' activities — NULL for 'strength'/'badge'. Lets real challenge
  -- progress (see `challenges` below) be a real SUM() instead of parsing it back out of `text`.
  distance_km NUMERIC,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- CREATE TABLE IF NOT EXISTS is a no-op on a table that already exists — this ALTER is what
-- actually adds distance_km to a database from before this column existed.
ALTER TABLE activities ADD COLUMN IF NOT EXISTS distance_km NUMERIC;

CREATE INDEX IF NOT EXISTS idx_activities_club_created ON activities(club_id, created_at DESC);

CREATE TABLE IF NOT EXISTS activity_kudos (
  activity_id UUID NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (activity_id, user_id)
);

-- Real comments on a club-mate's activity — several per activity, per user, unlike kudos (one
-- toggle per user). Moderated the same way as everything else user-generated: the blocklist filter
-- at submission (lib/moderation.js) plus the report mechanism (target_type 'comment').
CREATE TABLE IF NOT EXISTS activity_comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  activity_id UUID NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_activity_comments_activity_created ON activity_comments(activity_id, created_at ASC);

-- Real, permanent achievements — the client computes eligibility from data only it has (streak,
-- run history, elevation) and syncs earned keys up via api/clubs/syncBadges; once a row exists
-- here it stays (an achievement doesn't un-earn itself if the underlying streak later resets).
-- This is what makes badges visible on OTHER members' club profiles, not just your own device.
CREATE TABLE IF NOT EXISTS user_badges (
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  badge_key TEXT NOT NULL,
  earned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, badge_key)
);

-- Moderation (App Store guideline 1.2 — user-generated content: club names, display names, and
-- the activity feed need a block + report mechanism, not just a content filter at creation time).

CREATE TABLE IF NOT EXISTS blocks (
  blocker_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  blocked_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (blocker_id, blocked_id)
);

CREATE TABLE IF NOT EXISTS reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reporter_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  target_type TEXT NOT NULL, -- 'user' | 'club' | 'activity'
  target_id UUID NOT NULL,
  reason TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Any member can set a club challenge (a distance target by a deadline) — replaces what used to
-- be a fixed "100 km ce mois-ci" shown to everyone regardless of the real club. Progress is a real
-- SUM() over `activities.distance_km` logged since the challenge was created (see
-- api/clubs/[action].js), not tracked as a running counter here.
CREATE TABLE IF NOT EXISTS challenges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  club_id UUID NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  created_by UUID NOT NULL REFERENCES users(id),
  title TEXT NOT NULL,
  target_km NUMERIC NOT NULL,
  end_date DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_challenges_club_end ON challenges(club_id, end_date DESC);

-- Real APNs push (kudos received, a club-mate posts an activity) — one row per device a user has
-- signed in from. `token` is unique on its own (not per-user): the same physical device
-- re-registering after a sign-out/sign-in as a *different* account must move the token to the new
-- owner, not create a stale duplicate still pointing at the old one.
CREATE TABLE IF NOT EXISTS device_tokens (
  token TEXT PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  platform TEXT NOT NULL DEFAULT 'ios',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_device_tokens_user ON device_tokens(user_id);

-- Real Strava OAuth connection (see lib/strava.js, api/strava/[action].js) — tokens live only
-- server-side, the client_secret must never reach the app. `expires_at` drives when a stored
-- access token gets refreshed before the next call to Strava's API.
CREATE TABLE IF NOT EXISTS strava_connections (
  user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  strava_athlete_id BIGINT NOT NULL,
  access_token TEXT NOT NULL,
  refresh_token TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  connected_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- Corrective migrations (idempotent) — run after any of the tables above
-- already exist. Fresh databases get the same end state from the blocks below
-- because every statement here is a no-op once applied.
-- ============================================================================

-- Account deletion used to 500 with an FK violation for anyone who had created a club or a
-- challenge, or referred someone: these three columns referenced users(id) with no ON DELETE
-- action. App Store guideline 5.1.1(v) requires deletion to actually work — the creator's row
-- going away shouldn't take the club/challenge down with it, just detach it.
ALTER TABLE clubs ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE clubs DROP CONSTRAINT IF EXISTS clubs_created_by_fkey;
ALTER TABLE clubs ADD CONSTRAINT clubs_created_by_fkey
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE challenges ALTER COLUMN created_by DROP NOT NULL;
ALTER TABLE challenges DROP CONSTRAINT IF EXISTS challenges_created_by_fkey;
ALTER TABLE challenges ADD CONSTRAINT challenges_created_by_fkey
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE users DROP CONSTRAINT IF EXISTS users_referred_by_fkey;
ALTER TABLE users ADD CONSTRAINT users_referred_by_fkey
  FOREIGN KEY (referred_by) REFERENCES users(id) ON DELETE SET NULL;

-- One club per user, enforced by the database — the app-level check was check-then-insert, so a
-- double-submitted "join" raced into membership of two clubs at once, and every
-- `memberRows[0]` in the API then picked one arbitrarily.
CREATE UNIQUE INDEX IF NOT EXISTS uniq_club_members_user ON club_members(user_id);

-- Daily request counter behind api/coach.js's rate limit — keyed by user id when signed in,
-- client IP otherwise. Rows are tiny and only ever grow by one per key per day; prune old days
-- opportunistically if it ever matters.
CREATE TABLE IF NOT EXISTS coach_usage (
  key TEXT NOT NULL,
  day DATE NOT NULL,
  count INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (key, day)
);
