-- RunUp backend schema — Postgres (Vercel Postgres / Neon). Run this once against the database
-- connected to the Vercel project (see IOS_SETUP.md § "Backend (comptes, clubs, activités)").
--
-- v1 scope: a user belongs to at most one club at a time — enforced in application code
-- (api/clubs/*.js), not a DB constraint, so multi-club support later doesn't need a migration.

CREATE EXTENSION IF NOT EXISTS pgcrypto; -- gen_random_uuid()

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE,
  password_hash TEXT,
  apple_sub TEXT UNIQUE,
  google_sub TEXT UNIQUE,
  name TEXT NOT NULL,
  xp_total INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS clubs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  invite_code TEXT UNIQUE NOT NULL,
  created_by UUID NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS club_members (
  club_id UUID NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (club_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_club_members_user ON club_members(user_id);

CREATE TABLE IF NOT EXISTS activities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Idempotency key generated by the app (a UUID per completed run/goal) — a retried POST (flaky
  -- network) must not double-count XP or duplicate the feed entry.
  client_id UUID NOT NULL UNIQUE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  club_id UUID REFERENCES clubs(id) ON DELETE SET NULL,
  type TEXT NOT NULL, -- 'run' | 'strength' | 'badge'
  text TEXT NOT NULL, -- human-readable, e.g. "a couru 8.2 km · Sortie longue"
  xp_earned INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_activities_club_created ON activities(club_id, created_at DESC);

CREATE TABLE IF NOT EXISTS activity_kudos (
  activity_id UUID NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (activity_id, user_id)
);
